# Generated by Django 6.0.4 on 2026-05-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='S,M,L', help_text='Введіть розміри через кому без пробілів (наприклад: XS,S,M,L)', max_length=100, verbose_name='Доступні розміри'),
        ),
    ]
