# Generated by Django 6.0.4 on 2026-05-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_product_available_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата підписки')),
            ],
            options={
                'verbose_name': 'Підписник розсилки',
                'verbose_name_plural': 'Підписники розсилки',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адреса доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='S,M,L', help_text='Введіть розміри через кому без пробілів. Наприклад: XS,S,M,L', max_length=100, verbose_name='Доступні розміри'),
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оцінка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оцінки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='labs.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Оцінка товару',
                'verbose_name_plural': 'Оцінки товарів',
            },
        ),
    ]
