# Generated by Django 6.0.4 on 2026-05-15 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_order_user_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Назва категорії може містити тільки літери, цифри, пробіли та дефіс.', regex='^[А-Яа-яІіЇїЄєҐґA-Za-z0-9\\s\\-]+$')], verbose_name='Назва категорії'),
        ),
    ]
