# Generated by Django 6.0.4 on 2026-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Номер замовлення'),
        ),
    ]
